GET http://localhost:3000/api/customer/63bccf8f294df35ccb248ff2
###
POST http://localhost:3000/api/customer HTTP/1.1
Content-Type: application/json

{
  "ProductID": "007",
  "ProductType": "PV",
  "ProductName": "Thoma",
  "ProductPrice": 180
}

###
PUT http://localhost:3000/api/customer/63bccf8f294df35ccb248ff2 HTTP/1.1
Content-Type: application/json

{
  "ProductID": "006",
  "ProductType": "PV",
  "ProductName": "Ayaka",
  "ProductPrice": 180
}

###
DELETE  http://localhost:3000/api/customer/63bcca8148b4eee4638f6020 HTTP/1.1
